//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Petrol_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Balances = new HashSet<Balance>();
            this.Withdraws = new HashSet<Withdraw>();
        }
    
        public int CustomerID { get; set; }
        public string FullName { get; set; }
        public Nullable<long> MobileNumber { get; set; }
        public string ResidencePlace { get; set; }
        public string Address { get; set; }
        public string Photo { get; set; }
        public long SmartCardNumber { get; set; }
        public int VehicleNumber { get; set; }
    
        public virtual ICollection<Balance> Balances { get; set; }
        public virtual ICollection<Withdraw> Withdraws { get; set; }
    }
}
